config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
    resources :reviews
  end
  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
    presence: true, format: { with: VALID_EMAIL_REGEX}

  has_many :reviews
  has_many :restaurants, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
    @reviews = Review.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
        redirect_to @restaurant
    else
      render :edit
    end
  end

  def show
    @reviews = Review.all
    #ここにはレビューのコントローラーを書くことになりそう
  end

  def destroy
  end

private

  def restaurant_params
    params.require(:restaurant).permit(
      :name,
      :address,
      :phone,
      :URL,
      :image_url
      )
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @reviews = Review.all
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(
      restaurant_id: params[:restaurant_id],
      user_id: current_user.id,
      body: review_params["body"],
      score: review_params["score"]
    )
    if @review.save
      redirect_to restaurant_url(@review.restaurant)
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
        redirect_to @restaurant
    else
      render :edit
    end
  end



private

  def review_params
    params.require(:review).permit(
      :body,
      :score
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/restaurants">ぱくログ - Pakulog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
        <% if user_signed_in? %>
        <p class="navbar-text navbar-left">
        ログイン中：<%= current_user.email %>さん</p>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to '設定変更', edit_user_registration_path %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        </ul>
        <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to '新規登録', new_user_registration_path %></li>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
        </ul>
        <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>パクって載せよう美味しいお店！Pakulog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body>
<%= render partial: 'layouts/header' %>
<div class="container">
  <div class="row">
<%= yield %>
  </div>
</div>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, 'お店の名前' %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone, '電話番号' %><br>
    <%= f.text_field :phone, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :address, '住所' %><br>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :URL, 'URL' %><br>
    <%= f.text_field :URL, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image_url, '画像URL' %><br>
    <%= f.text_field :image_url, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<div class="col-xs-8 col-xs-offset-2">
  <h1>ぱくぱくレストラン情報の編集</h1>
  <%= render 'form' %>
  <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#delete-restaurant">レストラン情報を削除する</button>
</div>


<!-- 下記のモーダルは通常は隠れているので、どこに書いてもＯＫ -->
  <div class="modal fade" id="delete-customer">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">レストラン情報の削除</h4>
        </div>
        <div class="modal-body">
          <p><%= @restaurant.name %>の情報を削除しますか？</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
          <%= link_to '削除する', @restaurant, method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>

app/views/restaurants/index.html.erb
<div class="col-md-8">
      <h2>ぱくぱくレストラン一覧</h2>
      <% @restaurants.each do |restaurant| %>
  <div class="panel panel-default">
    <div class="panel-heading">
        <a href="/restaurants/<%= restaurant.id %>"><%= restaurant.name %></a>
         <span class="text-muted pull-right">追加日：<%= restaurant.created_at %></span>
    </div>
    <div class="panel-body">
        <div class="row">
          <div class="col-sm-2">
            <div class="thumbnail">
              <img src="<%= restaurant.image_url%>">
            </div> <!-- thumnail -->
          </div> <!-- col-sm-2 -->
          <div class="col-sm-10">
            <span class="stars"><span></span></span>
             <p>［ 口コミ<%= restaurant.reviews.count %>件 ］</p>
              <div class="panel panel-default">
                <div class="panel-body">
                <% restaurant.reviews.each do |review| %>
                <p>
                  <%= review.body %>
                  by ぱくぱく戦士<%= review.user.id %>号さん
                </p>
                <% end %>
                </div> <!-- panel-body -->
              </div> <!-- panel panel-default -->
          </div> <!-- col-sm-10 -->
        </div> <!-- row -->
      </div> <!-- panel-body -->
  </div>
        <% end %>
  <hr>
  <h2>最新口コミ</h2>
      <% @reviews.each do |review| %>
  <div class="col-sm-2">
          <div class="thumbnail">
            <img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
          </div><!-- /thumbnail -->
  </div><!-- /col-sm-2 -->
  <div class="panel panel-default">
    <div class="panel-heading">
        <div class="media-left">
          <small>ぱくぱく戦士<%= review.user.id %>号さんのレビュー</small>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
          <div class="col-sm-10">
                <p>
                  <%= review.body %>
                </p>
          </div> <!-- col-sm-10 -->
        </div> <!-- row -->
      </div> <!-- panel-body -->
  </div>
        <% end %>
</div>
<div class="col-lg-4">
    <a class="btn btn-success btn-block" href="/restaurants/new">新しくお店を登録する</a>
  <hr>
  <div class="panel panel-default">
    <div class="panel-heading">
      Inspiered by
    </div>
    <a href="http://tabelog.com/"><img src="http://sakutcafe.com/wp/wp-content/uploads/2014/01/tabelog_new.jpg"></a>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
    Sponsored Ad</div>
    <br />
  <a href="http://cookpad.com/loading/ct/?crid=27577&pid=1"><center><img src="http://img5-ak.cpcdn.com/ad4/914ba7ad166248f091b9b58df4dac80c.jpg?1424163415"></a></center>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="col-xs-8 col-xs-offset-2">
  <h1>ぱくぱくレストランの登録</h1>
  <%= render 'form' %>

  <%= link_to 'お店の一覧に戻る', restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div class="col-lg-12">
  <h1><%= @restaurant.name %></h1>
</div>

<div class="col-lg-8">
    <div class="col-sm-2">
            <div class="thumbnail">
              <img src="<%= @restaurant.image_url%>">
            </div> <!-- thumnail -->
    </div> <!-- col-sm-2 -->
    <p><strong>電話番号：</strong><%= @restaurant.phone %></p>
    <p><strong>住所：</strong><%= @restaurant.address %></p>
    <p><strong>HP：</strong><a href="<%= @restaurant.URL %>"><%= @restaurant.URL %></a></p>
    <%= link_to 'お店の情報を編集する', edit_restaurant_path, class: 'btn btn-primary' %>
    <%= link_to 'お店を削除する', restaurant_path, method: :delete, class: 'btn btn-danger'%>
    <%= link_to '口コミを投稿する', new_restaurant_review_path(@restaurant, @review), class: 'btn btn-success'%>
</div>
<div class="col-lg-12">
  <hr>
  <h3>お星さまはいくつ【平均】？</h3>
  <p><%= @restaurant.reviews.average(:score) %><span class="stars"><span></span></span></p>
  <hr>
</div>
<div class="col-lg-8">
  <h3>ぱくぱく隊員からの口コミ</h3>
  <% @restaurant.reviews.each do |review| %>
    <div class="panel panel-default">
        <div class="panel-heading">
        </div>
           <div class="panel-body">
                  <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://www.ikz.jp/hp/pac-man/gif/pac-ani.gif">
                    </div>
                    <div class="media-body">
                      <small>ぱくぱく隊員<%= review.user.id %>号さんの口コミ</small>
                    </div>
                    <hr>
                    <p>評価：<span class="stars"><span><%= review.score %></span></span></p>
                    <p><%= review.body %></p>
                    <%= link_to '口コミを編集する', edit_restaurant_review_path(@restaurant, review) , class: 'btn btn-default' %>
            </div>
          </div> <!-- panel-body -->
    </div>
  <% end %>
</div>
<div class="col-lg-4">
        <h3>おいしいお店みーつけた？</h3>
        <a class="btn btn-success btn-block" href="/restaurants/new">新しくお店を登録する</a>
      <hr>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>Inspiered by</h4>
        </div>
        <a href="http://tabelog.com/"><img src="http://sakutcafe.com/wp/wp-content/uploads/2014/01/tabelog_new.jpg"></a>
      </div>
      <div class="panel panel-default">
            <div class="panel-heading">
              <h4>Sponsored Ad</h4>
            </div>
        <br />
        <CENTER><a href="http://cookpad.com/loading/ct/?crid=27577&pid=1"><img src="http://img5-ak.cpcdn.com/ad4/914ba7ad166248f091b9b58df4dac80c.jpg?1424163415"></a></CENTER>
      </div>
</div>
  <hr>
  <div id="map" style="width: 330px; height: 100px;">
  <script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=false">
    function drawMap(address) {
        var geocoder = new google.maps.Geocoder();
        //住所から座標を取得する
        geocoder.geocode(
                {
                    'address': address,//検索する住所　〒◯◯◯-◯◯◯◯ 住所　みたいな形式でも検索できる
                    'region': 'jp'
                },
                function (results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {
                        google.maps.event.addDomListener(window, 'load', function () {
                            var map_tag = document.getElementById('map');
                            // 取得した座標をセット緯度経度をセット
                            var map_location = new google.maps.LatLng(results[0].geometry.location.k, results[0].geometry.location.D);
                            //マップ表示のオプション
                            var map_options =
                            {
                                zoom: 13,//縮尺
                                center: map_location,//地図の中心座標
                                //ここをfalseにすると地図上に人みたいなアイコンとか表示される
                                disableDefaultUI: true,
                                mapTypeId: google.maps.MapTypeId.ROADMAP//地図の種類を指定
                            };

                            //マップを表示する
                            var map = new google.maps.Map(map_tag, map_options);

                            //地図上にマーカーを表示させる
                            var marker = new google.maps.Marker({
                                position: map_location,//マーカーを表示させる座標
                                map: map//マーカーを表示させる地図
                            });
                        });
                    }
                }
        );
    }
    drawMap(住所);
  </script>
  </div>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/reviews/_form.html.erb
<%= form_for([@restaurant, @review]) do |f| %>
  <div class="form-group">
    <%= f.label :body, 'レビュー' %><br />
    <%= f.text_area :body, class: "form-control" %>
    <%= f.label :score, '星いくついただけますでしょうか？' %><br />
    <%= f.number_field :score, class: "form-control" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<div class="col-xs-8 col-xs-offset-2">
 <h1>口コミの編集</h1>
  <%= render 'form' %>
  <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#delete-review">口コミを削除する</button>
</div>

app/views/reviews/index.html.erb
review一覧的ななにか

app/views/reviews/new.html.erb
<div class="col-lg-12">
    <h1>口コミ登録</h1>
    <ul>
      <li>お店：<%= @restaurant.name %></li>
      <li>住所：<%= @restaurant.phone %></li>
      <li>住所：<%= @restaurant.address %></li>
      <li>URL：<%= @restaurant.URL %></li>
    </ul>

    <hr>
    <%= render 'form' %>
</div>

app/views/reviews/show.html.erb
show
<%= @review.body %>